### ISSUE TITLE
Interest in Resurrecting the project 

### ISSUE THREAD

**Issue by Azathothas** [lnxcz/leap#11]
Hi, I found this project interesting.
Are you interested in resurrecting it again?
If not, what are the major blockers?

**Comment by dfrnoch** [comment]
Hey, I've sadly lost interest in Linux and moved to macos, and since then stopped working on leap.

But you can check out this project: https://github.com/zyrouge/pho. It is basically the same thing I envisioned with leap.

**Comment by Azathothas** [comment]
I see..
